### ISSUE TITLE
Setting with equals sign in value parses incorrect key name and value

### ISSUE THREAD

**Issue by frednaughty** [kinghajj/mini#5]
Example: 
ConnectionString=host=example.com;username=example;password=example

Result: 
Key: ConnectionString=host=example.com;username=example;password=example
Value: example

Should Be:
Key: ConnectionString
Value: host=example.com;username=example;password=example

**Comment by kinghajj** [comment]
Should be fixed with your latest pull request. Guess I need to work on republishing this to Nuget.
