### ISSUE TITLE
Bug: spaces are lost when saving

### ISSUE THREAD

**Issue by Beluk** [kinghajj/mini#7]
Example:
The ini files contains the following entry. 
[5]
21=Timeout =
22=Timeout                  =

Im reading the inifile with 
var iniTarget = new IniDocument("file", System.Text.Encoding.Unicode);

After writing the ini file back to file the spaces between the second equal character is lost
iniTarget.Write("file");
Result:
[5]
21=Timeout=
22=Timeout=

**Comment by kinghajj** [comment]
Which version are you using? I just added a quick test against the current "master", and I can't replicate it.

        [TestMethod]
        public void EnsureSpacesWithinSettingValuesNotLost()
        {
            const string Issue7Example =
    @"[5]
    21=Timeout =
    22=Timeout =
    ";

            var stream = new StringReader(Issue7Example);
            var ini = new IniDocument(stream);
            var output = new StringWriter();
            ini.Write(output);
            var written = output.ToString();
            Assert.AreEqual(Issue7Example, written);
        }

**Comment by Beluk** [comment]
![2015-03-19 18_22_26-](https://cloud.githubusercontent.com/assets/10911904/6736417/f087945c-ce64-11e4-872c-7f16e9f33146.png)

I think the equal sign detection is wrong, because the line with two equal characters has only a key but no value

**Comment by kinghajj** [comment]
I'm pretty sure this bug was fixed by the PR for issue #5, I just haven't updated the NuGet package. I'll try to get that published tonight.

**Comment by Beluk** [comment]
I'm sorry i forgot to mention i was using 0.4.1, i will try again when you release the new package and report here

**Comment by kinghajj** [comment]
OK, 0.4.2.0 is pushed, let me know how it works for you.

**Comment by Beluk** [comment]
The problem is fixed with 0.4.2.0. Thank you for your support and for providing such a nice library.

**Comment by kinghajj** [comment]
Glad you find it useful! And thanks for helping improve it.
